### ISSUE TITLE
Error Message - Happens if I push the button to hide parts of my screens on OBS directly.

### ISSUE THREAD

**Issue by henningerc** [henningerc/RemoteControlStreamAssistant#29]
```
/home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/venv/bin/python /home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/main.py
Daarin ist online!
{'status': 'ok'}
Task exception was never retrieved
future: <Task finished name='Task-53' coro=<RemoteControlController.on_switch_scene_item() done, defined at /home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/Controller/RemoteControlController.py:27> exception=KeyError('DroidCam OBS')>
Traceback (most recent call last):
  File "/home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/Controller/RemoteControlController.py", line 28, in on_switch_scene_item
    await self.data.status.set_overlay_visible(data['scene-name'], data['item-name'], "True" if data['item-visible'] else "False")
  File "/home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/Controller/Status.py", line 22, in set_overlay_visible
    for lamp in self.overlay_lamps[scene][source]:
KeyError: 'DroidCam OBS'
Task exception was never retrieved
future: <Task finished name='Task-55' coro=<RemoteControlController.on_switch_scene_item() done, defined at /home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/Controller/RemoteControlController.py:27> exception=KeyError('Video.png (2)')>
Traceback (most recent call last):
  File "/home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/Controller/RemoteControlController.py", line 28, in on_switch_scene_item
    await self.data.status.set_overlay_visible(data['scene-name'], data['item-name'], "True" if data['item-visible'] else "False")
  File "/home/christoph/Entwicklung/Python/RemoteControlStreamingAssistant/Controller/Status.py", line 22, in set_overlay_visible
    for lamp in self.overlay_lamps[scene][source]:
KeyError: 'Video.png (2)'
```

**Comment by henningerc** [comment]
Fixed by checking for sources and scene before itterating it.
